# Generated by Django 5.0.7 on 2024-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(verbose_name='Номер поста')),
                ('author', models.IntegerField(verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
